#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = path.resolve(".");
const SKILL_DIR =
  "/Users/keshavperiwal/.codex/plugins/cache/openai-primary-runtime/presentations/26.601.10930/skills/presentations";
const NODE = "/Users/keshavperiwal/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node";
const WORKSPACE = path.join(
  ROOT,
  "outputs",
  "manual-20260605-deliverable2-efficient",
  "presentations",
  "task12-efficient",
);
const SLIDES_DIR = path.join(WORKSPACE, "slides");
const PREVIEW_DIR = path.join(WORKSPACE, "preview");
const LAYOUT_DIR = path.join(WORKSPACE, "layout");
const QA_DIR = path.join(WORKSPACE, "qa");
const OUTPUT_DIR = path.join(WORKSPACE, "output");
const FINAL_PPTX = path.join(OUTPUT_DIR, "Task1_Task2_Efficient_FoldSafe_Results.pptx");
const RESULT_PPTX = path.join(ROOT, "results", "Task1_Task2_Efficient_FoldSafe_Results.pptx");

function parseCsv(text) {
  const lines = text.trim().split(/\r?\n/);
  const headers = lines[0].split(",");
  return lines.slice(1).map((line) => {
    const values = [];
    let value = "";
    let quoted = false;
    for (let i = 0; i < line.length; i += 1) {
      const ch = line[i];
      if (ch === '"') {
        if (quoted && line[i + 1] === '"') {
          value += '"';
          i += 1;
        } else {
          quoted = !quoted;
        }
      } else if (ch === "," && !quoted) {
        values.push(value);
        value = "";
      } else {
        value += ch;
      }
    }
    values.push(value);
    return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""]));
  });
}

async function readCsv(relativePath) {
  return parseCsv(await fs.readFile(path.join(ROOT, relativePath), "utf8"));
}

function pct(value, digits = 1) {
  return `${(Number(value) * 100).toFixed(digits)}%`;
}

function num(value, digits = 3) {
  return Number(value).toFixed(digits);
}

function modelName(name) {
  return {
    linear_svm: "Linear SVM",
    random_forest: "Random Forest",
    svm_rbf: "RBF SVM",
    linear_svm_fresh: "Linear SVM + TSFresh",
    random_forest_fresh: "Random Forest + TSFresh",
    svm_rbf_fresh: "RBF SVM + TSFresh",
    patchtst: "PatchTST",
    resnet1d: "1D ResNet",
    lstm: "LSTM",
    gru: "GRU",
  }[name] ?? name;
}

function familyName(family) {
  return {
    feature_classical: "SelectKBest + classifier",
    feature_classical_tsfresh: "TSFresh selection + classifier",
    feature_neural: "Feature-vector neural",
  }[family] ?? family;
}

function js(value) {
  return JSON.stringify(value, null, 2);
}

async function writePlans() {
  await fs.mkdir(QA_DIR, { recursive: true });
  await fs.writeFile(
    path.join(WORKSPACE, "profile-plan.txt"),
    [
      "task mode: create",
      "primary deck-profile: engineering-platform",
      "secondary profile gates: appendix-heavy for metrics tables",
      "required proof objects: fold protocol, feature audit, selector comparison, model metrics, neural grid, confusion-matrix evidence",
      "source requirements: results/tables/*.csv and results/figures/*.png generated by the fold-safe Efficient pipeline",
      "QA gates: all reported metrics must come from CSV outputs; text and tables must render legibly at 16:9 thumbnail and full size",
    ].join("\n"),
    "utf8",
  );
  await fs.writeFile(
    path.join(WORKSPACE, "contact-sheet-plan.txt"),
    [
      "1 cover with metric rail",
      "2 horizontal protocol flow",
      "3 feature audit table plus feature-set note",
      "4 selector comparison ranked table",
      "5 final model metrics table",
      "6 neural grid comparison",
      "7 rendered figure evidence",
      "8 reproducibility appendix",
    ].join("\n"),
    "utf8",
  );
}

async function writeCommon(data) {
  const common = `
export const data = ${js(data)};

export const C = {
  ink: "#17202A",
  muted: "#5C6670",
  soft: "#EEF2F5",
  line: "#C9D2DA",
  teal: "#2F5F73",
  blue: "#3D6EA8",
  green: "#4F7D61",
  gold: "#B9822E",
  red: "#A95B50",
  white: "#FFFFFF",
};

export function addBase(slide, ctx, kicker, title, subtitle = "") {
  ctx.addShape(slide, { x: 0, y: 0, w: 1280, h: 720, fill: C.white });
  ctx.addShape(slide, { x: 0, y: 0, w: 1280, h: 10, fill: C.teal });
  ctx.addText(slide, { x: 56, y: 38, w: 230, h: 22, text: kicker.toUpperCase(), fontSize: 13, bold: true, color: C.teal, typeface: ctx.fonts.body });
  ctx.addText(slide, { x: 56, y: 66, w: 860, h: 78, text: title, fontSize: 30, bold: true, color: C.ink, typeface: ctx.fonts.title });
  if (subtitle) ctx.addText(slide, { x: 56, y: 150, w: 900, h: 42, text: subtitle, fontSize: 15, color: C.muted });
  ctx.addText(slide, { x: 1090, y: 674, w: 130, h: 18, text: "Task 1 + Task 2", fontSize: 12, color: C.muted, align: "right" });
}

export function addFooter(slide, ctx, text = "Fold-safe Efficient TSFresh pipeline") {
  ctx.addText(slide, { x: 56, y: 674, w: 780, h: 18, text, fontSize: 11, color: C.muted });
}

export function metric(slide, ctx, x, y, w, value, label, color = C.teal) {
  ctx.addShape(slide, { x, y, w, h: 96, fill: C.soft, line: ctx.line("#D8E0E6", 1) });
  ctx.addText(slide, { x: x + 18, y: y + 14, w: w - 36, h: 36, text: value, fontSize: 30, bold: true, color });
  ctx.addText(slide, { x: x + 18, y: y + 56, w: w - 36, h: 28, text: label, fontSize: 13, color: C.muted });
}

export function table(slide, ctx, rows, x, y, widths, rowH, opts = {}) {
  const headerFill = opts.headerFill ?? C.teal;
  const head = rows[0];
  let cx = x;
  head.forEach((cell, i) => {
    ctx.addShape(slide, { x: cx, y, w: widths[i], h: rowH, fill: headerFill });
    ctx.addText(slide, { x: cx + 8, y: y + 9, w: widths[i] - 16, h: rowH - 12, text: cell, fontSize: opts.headerSize ?? 12, bold: true, color: C.white, align: opts.align?.[i] ?? "left" });
    cx += widths[i];
  });
  rows.slice(1).forEach((row, r) => {
    cx = x;
    const fill = r % 2 === 0 ? "#F7F9FA" : C.white;
    row.forEach((cell, i) => {
      ctx.addShape(slide, { x: cx, y: y + rowH * (r + 1), w: widths[i], h: rowH, fill, line: ctx.line("#DDE5EA", 1) });
      ctx.addText(slide, { x: cx + 8, y: y + rowH * (r + 1) + 8, w: widths[i] - 16, h: rowH - 11, text: String(cell), fontSize: opts.bodySize ?? 12, color: C.ink, bold: opts.boldRows?.includes(r) ?? false, align: opts.align?.[i] ?? "left" });
      cx += widths[i];
    });
  });
}

export function bar(slide, ctx, x, y, w, label, value, max = 1, color = C.blue) {
  ctx.addText(slide, { x, y: y - 2, w: 165, h: 24, text: label, fontSize: 13, color: C.ink });
  ctx.addShape(slide, { x: x + 175, y, w, h: 18, fill: "#E6EBEF" });
  ctx.addShape(slide, { x: x + 175, y, w: Math.max(2, w * value / max), h: 18, fill: color });
  ctx.addText(slide, { x: x + 185 + w, y: y - 2, w: 70, h: 24, text: (value * 100).toFixed(1) + "%", fontSize: 13, bold: true, color });
}
`;
  await fs.writeFile(path.join(SLIDES_DIR, "common.mjs"), common, "utf8");
}

async function writeSlides(data) {
  await fs.mkdir(SLIDES_DIR, { recursive: true });
  const slides = [
    `import { C, addFooter, metric } from "./common.mjs";
export async function slide01(presentation, ctx) {
  const slide = presentation.slides.add();
  ctx.addShape(slide, { x: 0, y: 0, w: 1280, h: 720, fill: "#F8FAFB" });
  ctx.addShape(slide, { x: 0, y: 0, w: 1280, h: 12, fill: C.teal });
  ctx.addText(slide, { x: 70, y: 78, w: 860, h: 58, text: "Parkinson's Disease Detection from Gait", fontSize: 38, bold: true, color: C.ink, typeface: ctx.fonts.title });
  ctx.addText(slide, { x: 72, y: 146, w: 850, h: 34, text: "Task 1 + Task 2 results with fold-safe Efficient TSFresh feature extraction", fontSize: 20, color: C.muted });
  ctx.addShape(slide, { x: 74, y: 220, w: 1030, h: 1, fill: C.line });
  metric(slide, ctx, 78, 268, 220, "${data.cover.bestAcc}", "Best mean test accuracy", C.teal);
  metric(slide, ctx, 328, 268, 220, "${data.cover.bestAuc}", "Best mean test AUC", C.blue);
  metric(slide, ctx, 578, 268, 220, "5 folds", "Train / validation / test", C.green);
  metric(slide, ctx, 828, 268, 250, "84,430", "Efficient feature columns", C.gold);
  ctx.addText(slide, { x: 78, y: 430, w: 980, h: 68, text: "Main result: Linear SVM and Random Forest cross 80% under the corrected split protocol. TSFresh feature selection is useful in left/enhanced views, but the combined-view Linear SVM remains the strongest simple baseline.", fontSize: 21, color: C.ink });
  addFooter(slide, ctx, "Generated from results/tables/deliverable2_model_summary.csv");
  return slide;
}`,
    `import { C, addBase, addFooter } from "./common.mjs";
export async function slide02(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Protocol", "Every fold follows train -> validation -> test", "No feature selection, scaling, tuning, or classifier fit uses validation/test labels.");
  const items = [
    ["Train", "Efficient TSFresh fixed calculators", "Fit imputer, z-score, feature selection, classifier"],
    ["Validation", "No fitting of learned transforms", "Select classifier hyperparameters and neural grid candidate"],
    ["Test", "Held out until final evaluation", "Report accuracy, sensitivity, specificity, AUC"],
  ];
  items.forEach((item, i) => {
    const x = 92 + i * 380;
    ctx.addShape(slide, { x, y: 250, w: 300, h: 170, fill: i === 0 ? "#EAF2F4" : i === 1 ? "#EEF3EA" : "#F6EFE7", line: ctx.line("#CAD6DC", 1) });
    ctx.addText(slide, { x: x + 22, y: 272, w: 250, h: 30, text: item[0], fontSize: 23, bold: true, color: i === 0 ? C.teal : i === 1 ? C.green : C.gold });
    ctx.addText(slide, { x: x + 22, y: 316, w: 250, h: 34, text: item[1], fontSize: 14, color: C.ink });
    ctx.addText(slide, { x: x + 22, y: 358, w: 250, h: 42, text: item[2], fontSize: 13, color: C.muted });
    if (i < 2) {
      ctx.addShape(slide, { x: x + 320, y: 316, w: 38, h: 4, fill: C.line });
      ctx.addShape(slide, { x: x + 352, y: 309, w: 16, h: 16, geometry: "triangle", fill: C.line });
    }
  });
  ctx.addText(slide, { x: 92, y: 474, w: 1000, h: 58, text: "Important distinction: EfficientFCParameters is a fixed feature calculator, not a learned estimator. The cached subject features avoid repeated computation; all learned preprocessing and selection are still fit inside the training split.", fontSize: 18, color: C.ink });
  addFooter(slide, ctx);
  return slide;
}`,
    `import { C, addBase, addFooter, table } from "./common.mjs";
export async function slide03(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Task 1", "Fold distribution and feature extraction audit", "Efficient TSFresh produced consistent fold-local matrices for all train/validation/test splits.");
  table(slide, ctx, ${js(data.auditRows)}, 74, 224, [150, 150, 120, 190, 420], 46, { bodySize: 13, headerSize: 12, align: ["left", "left", "right", "right", "left"] });
  ctx.addShape(slide, { x: 78, y: 546, w: 1050, h: 62, fill: "#F7F9FA", line: ctx.line("#D9E2E8", 1) });
  ctx.addText(slide, { x: 98, y: 562, w: 1010, h: 34, text: "Audit check: every fold has 60 training, 20 validation, and 20 test subjects. Each Efficient matrix has 84,430 feature columns before train-fitted filtering/selection.", fontSize: 16, color: C.ink });
  addFooter(slide, ctx, "Feature audit: results/tables/deliverable2_fold_safe_feature_audit.csv");
  return slide;
}`,
    `import { C, addBase, addFooter, table } from "./common.mjs";
export async function slide04(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Feature Selection", "TSFresh selection helps in specific views, not universally", "Comparison uses the same folds, same Efficient feature matrices, and validation-selected classifiers.");
  table(slide, ctx, ${js(data.selectorRows)}, 64, 205, [130, 235, 230, 125, 125, 125, 105], 39, { bodySize: 11.5, headerSize: 11, align: ["left", "left", "left", "right", "right", "right", "right"] });
  ctx.addText(slide, { x: 78, y: 566, w: 940, h: 54, text: "Decision: keep both paths in the implementation. TSFresh select_features gives the best left/enhanced result; SelectKBest remains stronger for the combined Linear SVM.", fontSize: 17, color: C.ink });
  addFooter(slide, ctx, "Selector comparison: results/tables/deliverable2_feature_selection_comparison.csv");
  return slide;
}`,
    `import { C, addBase, addFooter, table } from "./common.mjs";
export async function slide05(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Task 2", "Final five-fold test results", "Mean metrics across the five test folds; test data is not used for model selection.");
  table(slide, ctx, ${js(data.bestRows)}, 66, 204, [120, 285, 235, 120, 120, 120, 100], 50, { bodySize: 12, headerSize: 11, align: ["left", "left", "left", "right", "right", "right", "right"] });
  ctx.addText(slide, { x: 80, y: 484, w: 455, h: 72, text: "Best accuracy: 83.0% across combined, enhanced, and right-foot views. Best AUC: 0.912 from left-foot Linear SVM + TSFresh selection.", fontSize: 18, bold: true, color: C.ink });
  ctx.addText(slide, { x: 620, y: 484, w: 490, h: 76, text: "Professor reference: Linear SVM around 80%. Corrected fold-safe Efficient features now exceed that while preserving validation/test separation.", fontSize: 18, color: C.ink });
  addFooter(slide, ctx, "Best models: results/tables/deliverable2_best_models_by_scope.csv");
  return slide;
}`,
    `import { C, addBase, addFooter, bar, table } from "./common.mjs";
export async function slide06(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Neural Grid", "Feature-vector neural models improve with tuning but trail classical models", "Grid: k_features in {100, 200, 400}, learning rate in {0.0003, 0.0008}, weight decay in {0.0001, 0.001}.");
  const bars = ${js(data.neuralBars)};
  bars.forEach((row, i) => bar(slide, ctx, 84, 228 + i * 48, 300, row.label, row.value, 0.85, i === 0 ? C.blue : C.green));
  table(slide, ctx, ${js(data.neuralRows)}, 730, 216, [130, 140, 105, 105], 42, { bodySize: 11.5, headerSize: 11, align: ["left", "left", "right", "right"] });
  ctx.addText(slide, { x: 84, y: 546, w: 520, h: 50, text: "PatchTST is the best neural option after grid tuning, but the feature-vector neural models do not surpass the best SVM/RF baselines.", fontSize: 17, color: C.ink });
  addFooter(slide, ctx, "Neural grid: results/tables/deliverable2_feature_neural_fold_metrics.csv");
  return slide;
}`,
    `import { C, addBase, addFooter } from "./common.mjs";
export async function slide07(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Evidence", "Summary charts and confusion matrices", "Rendered directly from the final merged fold-safe result tables.");
  await ctx.addImage(slide, { path: "${path.join(ROOT, "results/figures/deliverable2_metric_summary.png").replaceAll("\\", "/")}", x: 68, y: 220, w: 560, h: 300, fit: "contain" });
  await ctx.addImage(slide, { path: "${path.join(ROOT, "results/figures/deliverable2_best_confusion_matrices.png").replaceAll("\\", "/")}", x: 676, y: 220, w: 520, h: 300, fit: "contain" });
  ctx.addText(slide, { x: 82, y: 548, w: 1080, h: 46, text: "The confusion matrices are pooled across the test predictions for each best-by-scope model, after validation-selected model choices were fixed.", fontSize: 16, color: C.ink });
  addFooter(slide, ctx, "Figures: results/figures/deliverable2_metric_summary.png and deliverable2_best_confusion_matrices.png");
  return slide;
}`,
    `import { C, addBase, addFooter } from "./common.mjs";
export async function slide08(presentation, ctx) {
  const slide = presentation.slides.add();
  addBase(slide, ctx, "Reproducibility", "Files generated for review and rerun", "The notebook and runner are set up so the experiment can be rerun without changing the protocol.");
  const lines = [
    ["Notebook", "Task1_Task2_Efficient_FoldSafe.ipynb"],
    ["Runner", "scripts/run_deliverable2.py -> scripts/run_deliverable2_foldsafe.py"],
    ["Feature matrices", "results/fold_features/Fold_*/{training,validation,test}_feature_matrix_efficient.csv"],
    ["Result tables", "results/tables/deliverable2_model_summary.csv"],
    ["Feature selection comparison", "results/tables/deliverable2_feature_selection_comparison.csv"],
  ];
  lines.forEach((row, i) => {
    const y = 214 + i * 62;
    ctx.addText(slide, { x: 96, y, w: 250, h: 28, text: row[0], fontSize: 15, bold: true, color: C.teal });
    ctx.addText(slide, { x: 360, y, w: 760, h: 28, text: row[1], fontSize: 15, color: C.ink });
    ctx.addShape(slide, { x: 96, y: y + 40, w: 1010, h: 1, fill: "#E3E9EE" });
  });
  ctx.addText(slide, { x: 96, y: 562, w: 970, h: 44, text: "Recommended presentation claim: the corrected fold-safe protocol is now defensible, and Efficient TSFresh + classical classifiers is the current best non-Mamba baseline.", fontSize: 17, bold: true, color: C.ink });
  addFooter(slide, ctx);
  return slide;
}`,
  ];

  for (let i = 0; i < slides.length; i += 1) {
    await fs.writeFile(path.join(SLIDES_DIR, `slide-${String(i + 1).padStart(2, "0")}.mjs`), slides[i], "utf8");
  }
}

async function main() {
  await fs.mkdir(SLIDES_DIR, { recursive: true });
  await fs.mkdir(PREVIEW_DIR, { recursive: true });
  await fs.mkdir(LAYOUT_DIR, { recursive: true });
  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await writePlans();

  const best = await readCsv("results/tables/deliverable2_best_models_by_scope.csv");
  const audit = await readCsv("results/tables/deliverable2_fold_safe_feature_audit.csv");
  const selector = await readCsv("results/tables/deliverable2_feature_selection_comparison.csv");
  const summary = await readCsv("results/tables/deliverable2_model_summary.csv");

  const bestRows = [
    ["Scope", "Best family", "Model", "Accuracy", "Sensitivity", "Specificity", "AUC"],
    ...best.map((row) => [
      row.scope,
      familyName(row.family),
      modelName(row.model),
      pct(row.test_accuracy_mean),
      pct(row.test_sensitivity_mean),
      pct(row.test_specificity_mean),
      num(row.test_auc_mean),
    ]),
  ];

  const auditRows = [
    ["Fold", "Split", "Rows", "Feature cols", "Protocol note"],
    ...audit.slice(0, 6).map((row) => [row.fold, row.split, row.rows, Number(row.feature_columns).toLocaleString(), "fixed calculators; train-fitted learned steps"]),
  ];

  const selectorRows = [
    ["Scope", "Selector", "Model", "Acc.", "Sens.", "Spec.", "AUC"],
    ...["combined", "enhanced", "left", "right"].flatMap((scope) =>
      selector
        .filter((row) => row.scope === scope)
        .sort((a, b) => Number(b.test_accuracy_mean) - Number(a.test_accuracy_mean) || Number(b.test_auc_mean) - Number(a.test_auc_mean))
        .slice(0, 2)
        .map((row) => [
          row.scope,
          row.selector.replace("sklearn.", "").replace("tsfresh.", ""),
          modelName(row.model),
          pct(row.test_accuracy_mean),
          pct(row.test_sensitivity_mean),
          pct(row.test_specificity_mean),
          num(row.test_auc_mean),
        ]),
    ),
  ];

  const neuralSummary = summary
    .filter((row) => row.family === "feature_neural")
    .sort((a, b) => Number(b.test_accuracy_mean) - Number(a.test_accuracy_mean) || Number(b.test_auc_mean) - Number(a.test_auc_mean));
  const neuralRows = [
    ["Scope", "Model", "Accuracy", "AUC"],
    ...neuralSummary.slice(0, 5).map((row) => [row.scope, modelName(row.model), pct(row.test_accuracy_mean), num(row.test_auc_mean)]),
  ];
  const neuralBars = neuralSummary.slice(0, 6).map((row) => ({
    label: `${row.scope} ${modelName(row.model)}`,
    value: Number(row.test_accuracy_mean),
  }));

  const topAcc = best.reduce((acc, row) => Math.max(acc, Number(row.test_accuracy_mean)), 0);
  const topAuc = best.reduce((acc, row) => Math.max(acc, Number(row.test_auc_mean)), 0);
  const data = {
    cover: { bestAcc: pct(topAcc), bestAuc: num(topAuc) },
    bestRows,
    auditRows,
    selectorRows,
    neuralRows,
    neuralBars,
  };

  await writeCommon(data);
  await writeSlides(data);

  const buildScript = path.join(SKILL_DIR, "scripts/build_artifact_deck.mjs");
  const result = spawnSync(
    NODE,
    [
      buildScript,
      "--workspace",
      WORKSPACE,
      "--slides-dir",
      SLIDES_DIR,
      "--out",
      FINAL_PPTX,
      "--preview-dir",
      PREVIEW_DIR,
      "--layout-dir",
      path.join(LAYOUT_DIR, "final"),
      "--contact-sheet",
      path.join(PREVIEW_DIR, "contact-sheet.png"),
      "--slide-count",
      "8",
    ],
    { cwd: ROOT, encoding: "utf8" },
  );
  if (result.status !== 0) {
    console.error(result.stdout);
    console.error(result.stderr);
    process.exit(result.status ?? 1);
  }
  await fs.copyFile(FINAL_PPTX, RESULT_PPTX);
  console.log(result.stdout);
  console.log(JSON.stringify({ finalPptx: RESULT_PPTX, workspace: WORKSPACE }, null, 2));
}

main().catch((error) => {
  console.error(error.stack || error.message || String(error));
  process.exit(1);
});
